version: "2.2"

services:
  data_db:
    image: postgres:14.7
    container_name: "db.data.skelmis.co.nz"
    restart: always
    command: -p 2201
    ports:
      - "2201:2201"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: data_skelmis_co_nz
      POSTGRES_USER: data_autohelp_db_user
      POSTGRES_PASSWORD: product-defeat-follow-worshiper-swimwear-drown
    volumes:
      - .db:/var/lib/postgresql/data
  data_web:
    image: ghcr.io/skelmis/data.skelmis.co.nz:master
    container_name: "web_data.skelmis.co.nz"
    restart: always
    ports:
      - "2200:2200"
    depends_on:
      - data_db
    cpus: 1
    mem_limit: 1g
    mem_reservation: 256m
    environment:
      SERVING_DOMAIN: "data.skelmis.co.nz"
      POSTGRES_HOST: db.data.skelmis.co.nz
      POSTGRES_DB: its_a_db_woo
      POSTGRES_USER: its_a_db_woo_user
      POSTGRES_PASSWORD: its_a_db_woo_password_for_db_user
      POSTGRES_PORT: 2201

#networks:
#  default:
#    name: spook
#    external: true